FROM python:3.9

# set the working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add requirements
COPY ./requirements.txt /usr/src/app/requirements.txt

#install the requirements
RUN pip install -r requirements.txt

#add app
COPY . /usr/src/app

# run server
CMD python3.9 manage.py run -h 0.0.0.0